language: node_js
node_js:
  - 0.10
  #- 6
  #- 8
before_install:
  - npm install -g npm@2.15.0
  - npm install -g node-gyp@3.1.0
after_success:
  - npm install -g nyc@8.1.0
  - npm install -g codecov
  - nyc --reporter lcov npm test && codecov
